<?php

namespace App\Models;

use Eloquent;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

/**
 * Class Brand
 * @mixin Eloquent
 */
class Brand extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'slug',
        'web_url',
        'description',
        'status',
        'created_by',
        'updated_by'
    ];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function (Brand $brand) {
            $brand->slug = slug($brand->name);
            $brand->created_by = Auth::id() ?? 1;
            $brand->updated_by = Auth::id() ?? 1;
        });

        self::updating(function (Brand $brand) {
            $brand->slug = slug($brand->name);
            $brand->updated_by = Auth::id();
        });
    }
}
