<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class Setting extends Model
{
    use HasFactory;

    const IMAGE_DIMENSIONS = [
        'footer_logo' => [
            'h' => 100,
            'w' => 200
        ],
        'header_logo' => [
            'h' => 150,
            'w' => 250
        ]
    ];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function ($item) {
            $item->created_by = Auth::id() ?? 1;
            $item->updated_by = Auth::id() ?? 1;
        });

        self::updating(function ($item) {
            $item->updated_by = Auth::id();
        });
    }

    public function images(): \Illuminate\Database\Eloquent\Relations\MorphMany
    {
        return $this->morphMany(Image::class, 'imageable');
    }
}
